Try again

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -92,23 +92,21 @@ jobs:
             g++ \
             make \
             cmake \
-            libtbb-dev \
-            libatlas-base-dev \
-            libjpeg-dev \
-            libpng-dev \
-            libtiff-dev \
-            libopenjp2-7-dev \
-            zlib1g-dev
+            libtbb \
+            libatlas-base \
+            libjpeg \
+            libpng \
+            libtiff \
+            libopenjp2-7 \
+            zlib1g
 
       - name: Verify OpenCvSharp Libraries
         if: matrix.config.osfamily == 'linux'
         run: |
-          find -iname libOpenCvSharpExtern.so
-          if find -iname libOpenCvSharpExtern.so -exec ldd {} \; \
-                | grep "not found"; then
-            echo "unresolved dependencies detected"
-            exit 1
-          fi
+          find Straights.Image.Tests -iname libOpenCvSharpExtern.so
+          find Straights.Image.Tests -iname libOpenCvSharpExtern.so -exec ldd {} \; \
+              | tee /dev/stderr \
+              | grep -q "found" && exit 1  # fail step if any missing libs are reported
 
       - name: Test
         run: >
